spring:
  devtools:
    restart:
      enabled: true
  application:
    name: auncel-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auncel_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    #        password: 123456
    port: 6379
    host: 49.234.72.82
server:
  port: 3100
  servlet:
    session:
      timeout: 24h
      cookie:
        domain: "auncel.top"

auncel:
  password: password
  salt: d246ca5b089346e2