spring:
  cloud:
    nacos:
      discovery:
        server-addr: '101.37.29.47:6399'
        heart-beat-timeout: 10000
#      config:
#        timeout: 10000
#        server-addr: '101.37.29.47:6399'
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auncel_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl